version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ifceeventos
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
